Strip whitespace before parsing in seval
JuliaPy/PythonCall.jl pull request #380
Opened 2023-10-10 02:48 UTC by LilithHafner

Fixes #379 

I'm not sure how to add tests for this. I don't see tests from the Python side.

2023-10-10 08:13 UTC, cjdoris commented
Thanks! You could use https://github.com/JuliaPy/PythonCall.jl/issues/379#issuecomment-1754652793 as the basis of some tests.

2023-10-10 12:29 UTC, LilithHafner commented
Okay, I put tests in `test/utils.jl` and tested this from the Julia side. Are there no CI tests with Python as the host language?

2023-10-10 12:38 UTC, cjdoris requested changes

2023-10-10 12:38 UTC, cjdoris commented on test/utils.jl
> +end
Could you move the test to https://github.com/JuliaPy/PythonCall.jl/blob/5f56a9b96b867a9f6742ab1d1e2361abd844e19f/test/jlwrap.jl#L189 please?

2023-10-10 12:40 UTC, cjdoris commented on test/utils.jl
> +end
Also these tests are failing because `m.seval(...)` returns a `Py`.

2023-10-10 12:42 UTC, cjdoris commented
> Are there no CI tests with Python as the host language?

There are, under `pytest`. These get run in CI along with the Julia tests.

Currently all the Python-side tests do is check that `import juliacall` doesn't raise an exception.

2023-10-10 12:52 UTC, LilithHafner commented
My inclination would be to test this on the python side the way it came up in the wild, like this:

2023-10-10 12:54 UTC, LilithHafner commented
Where is `test_import` called from?

2023-10-10 13:47 UTC, LilithHafner commented
FWIW this is not a problem in Julia 1.10+, but it's still probably worth fixing here for compatibility with 1.6/1.9.

2023-10-10 19:38 UTC, cjdoris commented
> My inclination would be to test this on the python side the way it came up in the wild, like [this](https://github.com/JuliaPy/PythonCall.jl/pull/380/commits/bef8c6a5bd85daa771b01759409bc4cfccffcf4b)

I'd prefer the tests back in Julia, since that's where it's defined (it's more of a unit test that way).

2023-10-10 19:40 UTC, cjdoris commented
> Where is `test_import` called from?

It's called by magic. When you run the [`pytest`](https://docs.pytest.org/en/7.4.x/) program, it searches for functions called `test_something` and executes them.

2023-10-10 20:26 UTC, LilithHafner commented
So I'm assuming the new function I added is also called by magic. Is that test acceptable to you or would you like me to move it back to the Julia side?

2023-10-10 20:37 UTC, cjdoris commented
> So I'm assuming the new function I added is also called by magic. Is that test acceptable to you or would you like me to move it back to the Julia side?

Yes indeed. Back to Julia please - I'd like to keep the Python tests restricted to just the things extra that JuliaCall itself gives you.

2023-10-11 17:37 UTC, merged

2023-10-11 17:37 UTC, cjdoris commented
Thanks muchly!